name: Build APK (Manual)

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Clean project
      run: ./gradlew clean
      
    - name: Build debug APK
      if: ${{ inputs.build_type == 'debug' }}
      run: ./gradlew assembleDebug
      
    - name: Build release APK
      if: ${{ inputs.build_type == 'release' }}
      run: ./gradlew assembleRelease
      
    - name: Upload debug APK
      if: ${{ inputs.build_type == 'debug' }}
      uses: actions/upload-artifact@v3
      with:
        name: fast-app-drawer-debug
        path: app/build/outputs/apk/debug/*.apk
        
    - name: Upload release APK
      if: ${{ inputs.build_type == 'release' }}
      uses: actions/upload-artifact@v3
      with:
        name: fast-app-drawer-release
        path: app/build/outputs/apk/release/*.apk
        
    - name: Show APK info
      run: |
        echo "✅ APK built successfully!"
        echo "📱 Build type: ${{ inputs.build_type }}"
        echo "📦 APK location: app/build/outputs/apk/${{ inputs.build_type }}/"
        echo "⬇️ Download from the Artifacts section above" 