name: Test Only (Fast)

on:
  workflow_dispatch:
  push:
    paths:
      - '**/test/**'
      - '**/*Test.kt'
      - '**/*Test.java'

jobs:
  test:
    name: Quick Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run unit tests only
      run: ./gradlew test --no-daemon --stacktrace --continue
      
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Fast Test Results
        path: '**/build/test-results/test*/TEST-*.xml'
        reporter: java-junit
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: fast-test-results
        path: |
          **/build/test-results/
          **/build/reports/tests/

    - name: Test Summary
      if: always()
      run: |
        echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Unit tests completed" >> $GITHUB_STEP_SUMMARY
        echo "- Check the test reports in artifacts for detailed results" >> $GITHUB_STEP_SUMMARY
        echo "- Any failures will be shown in the Test Results tab" >> $GITHUB_STEP_SUMMARY 